apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  MONGO_URI: "mongodb://<USERNAME>:<PASSWORD>@mongodb.opspilot.svc.cluster.local:27017/opspilot?authSource=admin"
  REDIS_URL: "redis://redis.opspilot.svc.cluster.local:6379"
  JWT_ACCESS_SECRET: "<CHANGE_ME>"
  JWT_REFRESH_SECRET: "<CHANGE_ME>"
  JWT_ACCESS_EXPIRES: "15m"
  JWT_REFRESH_EXPIRES: "7d"
  COOKIE_SECRET: "<CHANGE_ME>"
