apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../k8s
  - ../k8s/backend-secret.yml
  - ../k8s/mongodb-secret.yml
  - ../k8s/redis-secret.yml
  - ingress-kind.yml

patches:
  - path: backend-image-patch.yml
  - path: frontend-image-patch.yml
